### ISSUE TITLE
Use new version of scanner, when it updates

### ISSUE THREAD

**Issue by elgohr** [elgohr/concourse-blackduck#12]
At the moment it's hardcoded to 5.4.0, so it would fail, when it gets updated.

**Comment by nikslos** [comment]
Thanks for caring at the moment there is the version 5.5.1 in your container (latest) on the docker-hub, which is causing the example-pipeline to fail. 
$ ls opt/resource/
check  in  out	synopsys-detect-5.5.1.jar

**Comment by elgohr** [comment]
There you go https://github.com/elgohr/concourse-blackduck/commit/555886a3c1cc897fd018e322cbf40bd4d0559ce9
